# Site settings
title: Social Impact Lab
email: hello@simlab.org
description: "We are Social Impact Lab. We use inclusive technologies to build systems and services that are more accessible, responsive, and resilient."
baseurl: ""
url: "http://simlab.org"
twitter_username: simlab
github_username:  socialimpactlab

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
- staff
